### ISSUE TITLE
problem on the demonstration web-site

### ISSUE THREAD

**Issue by wongtaksum** [UniversalDependencies/UD_Classical_Chinese-Kyoto#3]
Thank you for creating such a wonderful resource!
I just found that your demonstration web-site only work with the example sentence but it does not work when I  input other sentences. Could you fix it?
http://kanji.zinbun.kyoto-u.ac.jp/~yasuoka/kyodokenkyu/2018-12-01.html

**Comment by KoichiYasuoka** [comment]
@wongtaksum I confirmed that [「漢文の依存文法解析と返り点の関係について」試作サイト](http://kanji.zinbun.kyoto-u.ac.jp/~yasuoka/kyodokenkyu/2018-12-01.html) works well with other examples: 孟子見梁惠王, 有朋自遠方來, etc. However it does not work with 簡化字 because it is 試作サイト (only for testing). Please use [UD-Kundoku](https://github.com/KoichiYasuoka/UD-Kundoku) instead.
