### ISSUE TITLE
New copula 是 needed

### ISSUE THREAD

**Issue by KoichiYasuoka** [UniversalDependencies/UD_Classical_Chinese-Kyoto#5]
Hi @dan-zeman recently we added 佛說阿彌陀經, in which 是 is used as the copula verb instead of 爲. In Chinese language, the ancient copula was 爲 (originally a VERB), and the nowadays copula is 是 (originally a PRON). In fact 佛說阿彌陀經 is a very early example to use 是 as a copula. How do we add 是 as a copula?

**Comment by dan-zeman** [comment]
I have added "This is the ancient copula (originally a VERB)." to the Deficient Paradigm field of 爲 in [https://quest.ms.mff.cuni.cz/udvalidator/cgi-bin/unidep/langspec/specify_auxiliary.pl?lcode=lzh](https://quest.ms.mff.cuni.cz/udvalidator/cgi-bin/unidep/langspec/specify_auxiliary.pl?lcode=lzh). It should enable adding 是 as a secondary copula.

However, the form currently does not provide any `Add` buttons because it requires the missing documentation of nine auxiliaries (儀 宜 得 敢 欲 肯 被 足 須) first.

**Comment by KoichiYasuoka** [comment]
Just included 是 as a copula. Thank you @dan-zeman !
